name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '* 13 * * *'

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Unit tests
      run: ./gradlew testDebugUnitTest  
    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }}

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: app/build/outputs/apk/debug
    
    - name: Slack - Send Msg
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: workflow,job,commit,repo,author,took,ref
        author_name: ji
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_URL }}
      if: always()
    
    - name: Slack - Upload APK 
      uses: MeilCli/slack-upload-file@v3
      with: 
        slack_token: ${{ secrets.SLACK_TOKEN }} 
        channel_id: ${{ secrets.SLACK_CHANNEL }}
        initial_comment: 'APK File Upload'
        file_name: 'app'
        file_path: 'app/build/outputs/apk/debug'
